FROM python:3.10-slim-buster

RUN pip install --no-cache-dir paperbee

WORKDIR /app

COPY ./config.yml ./google-credentials.json .

EXPOSE 5000

CMD ["paperbee", "post", "--config", "/app/config.yml", "--since", "30"]

