FROM python:3.13-slim
COPY --from=ghcr.io/astral-sh/uv:0.8.0 /uv /uvx /bin/

RUN apt-get update -y && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY src /app/src

COPY assets /app/src

COPY pyproject.toml uv.lock run_bot.sh .python-version .

EXPOSE 5000

RUN uv sync --locked

CMD ["./run_bot.sh"]

